# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChooseFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ChooseFilter(object):
    def setupUi(self, Dialog_ChooseFilter):
        Dialog_ChooseFilter.setObjectName("Dialog_ChooseFilter")
        Dialog_ChooseFilter.resize(417, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/roskazna.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_ChooseFilter.setWindowIcon(icon)
        Dialog_ChooseFilter.setStyleSheet("#Dialog_ChooseFilter {background-color: rgba(254,214,0,200)}\\n\n"
".QPushButton {background-color: rgba(143, 144, 146, 200)}\\n\n"
".QPushButton:hover{ background-color: rgba(143, 144, 146, 250)}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_ChooseFilter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(Dialog_ChooseFilter)
        self.listWidget.setStyleSheet(".QListWidget {background-color: rgba(143, 144, 146, 100);\n"
"border-radius:8px;}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(Dialog_ChooseFilter)
        self.pushButton.setStyleSheet(".QPushButton {background-color: rgba(143, 144, 146, 80)}\n"
".QPushButton:hover{ background-color: rgba(143, 144, 146, 130)}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog_ChooseFilter)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ChooseFilter)

    def retranslateUi(self, Dialog_ChooseFilter):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ChooseFilter.setWindowTitle(_translate("Dialog_ChooseFilter", "Выбор объектов для анализа"))
        self.pushButton.setText(_translate("Dialog_ChooseFilter", "Добавить"))
        
import images_qr
